version: '3'

volumes:
  pg_data:
  static:
  media:
    driver: local

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data

  backend:
    image: off1ght/kittygram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/

  frontend:
    env_file: .env
    image: off1ght/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: off1ght/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/
